---
title: seforim.app
logo: "/uploads/default/original/1X/d0e2fb4253132312b6ada410373eac531f6b2c1a.svg"
suggested_topics: '0'
post_menu: edit|delete|admin|reply
default_dark_mode_color_scheme_id: '7'
enable_badges: 'false'
auth_skip_create_confirm: 'true'
auth_overrides_email: 'true'
auth_overrides_username: 'true'
auth_overrides_name: 'true'
enable_discourse_connect: 'true'
discourse_connect_url: https://seforim.app/sso
discourse_connect_secret: your secret
discourse_connect_overrides_bio: 'true'
discourse_connect_overrides_avatar: 'true'
discourse_connect_overrides_location: 'true'
discourse_connect_overrides_website: 'true'
min_username_length: '1'
max_username_length: '60'
unicode_usernames: 'true'
email_editable: 'false'
logout_redirect: https://seforim.app/sso?logout=true
prioritize_username_in_ux: 'false'
min_post_length: '1'
min_first_post_length: '1'
body_min_entropy: '0'
min_topic_title_length: '1'
title_min_entropy: '0'
allow_uncategorized_topics: 'true'
allow_duplicate_topic_titles: 'true'
title_max_word_length: '99999'
display_name_on_posts: 'true'
embed_set_canonical_url: 'true'
new_user_notice_tl: '4'
returning_user_notice_tl: '4'
download_remote_images_to_local: 'false'
default_trust_level: '1'
allowed_iframes: https://www.google.com/maps/embed?|https://www.openstreetmap.org/export/embed.html?|https://calendar.google.com/calendar/embed?|https://codepen.io/|https://www.instagram.com|https://discuss.seforim.app/discobot/certificate.svg|http://discuss.seforim.app/discobot/certificate.svg|https://seforim.app
navigation_menu: header dropdown
default_sidebar_categories: 2|3|4
educate_until_posts: '0'
default_composer_category: '4'
default_email_digest_frequency: '1440'
disable_discourse_narrative_bot_welcome_post: 'true'
